# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: greeting.proto for package 'greeting'

require 'grpc'
require 'greeting_pb'

module Greeting
  module Greeter
    # The greeting service definition.
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'greeting.Greeter'

      # Sends a greeting
      rpc :SayHello, HelloRequest, HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
