# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeting.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "greeting.HelloRequest" do
    optional :name, :string, 1
  end
  add_message "greeting.HelloReply" do
    optional :message, :string, 1
  end
end

module Greeting
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("greeting.HelloRequest").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("greeting.HelloReply").msgclass
end
